--- # My condition playbook 
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: install apache server on debion
      command: apt-get -y install apache2
      when: ansible_os_family == "Debion"
    - name: install apache server on redhat
      command: yum -y install httpd
      when: ansible_os_family == "RedHat"
