--- #My loops playbook
- hosts: developer
  user: ck1
  become: yes
  connection: ssh
  tasks:
    - name: add a list of users
      user: name='{{item}}' state=present
      with_items:
        - ckraj
        - sachin-tendulkar
        - chhagan
        - vasco-d-gama
