--- # My variable file for testing perpose
- hosts: developer
  user: ck1
  become: yes
  connection: ssh
  vars:
    pkgname: httpd
  tasks:
    - name: install HTTPD server on my linux
      action: yum name='{{pkgname}}' state=present
